// Generates tokens.css, custom-media.css, breakpoints.js and dist/tokens/tokens.json from tokens/tokens.json.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = JSON.parse(readFileSync(resolve(root, "tokens/tokens.json"), "utf8"));

/** Resolve `{a.b.c}` aliases against the raw token tree. */
export function resolveAlias(value, tree, seen = new Set()) {
  if (typeof value !== "string") return value;
  return value.replace(/\{([^}]+)\}/g, (_, path) => {
    if (seen.has(path)) throw new Error(`Circular token alias: ${path}`);
    const target = path.split(".").reduce((node, key) => (node == null ? undefined : node[key]), tree);
    if (target === undefined) throw new Error(`Unknown token alias: {${path}}`);
    const leaf = typeof target === "object" && "$value" in target ? target.$value : target;
    if (typeof leaf !== "string") throw new Error(`Alias {${path}} does not point to a plain value`);
    return resolveAlias(leaf, tree, new Set([...seen, path]));
  });
}

/** Flatten the tree into a list of { name, type, value | { light, dark } }. */
export function flatten(tree) {
  const out = [];
  const walk = (node, path, type) => {
    for (const [key, val] of Object.entries(node)) {
      if (key.startsWith("$")) continue;
      const p = [...path, key];
      const t = (val && val.$type) || type;
      if (typeof val === "string") out.push({ path: p, type: t, value: resolveAlias(val, tree) });
      else if (val && "$value" in val) out.push({ path: p, type: t, value: resolveAlias(val.$value, tree) });
      else if (val && "light" in val && "dark" in val) out.push({ path: p, type: t, value: { light: resolveAlias(val.light, tree), dark: resolveAlias(val.dark, tree) } });
      else if (val && typeof val === "object") walk(val, p, t);
    }
  };
  walk(tree, [], undefined);
  return out;
}

const cssName = (t) => `--iv-${t.path.join("-")}`;

export function emitCss(tokens) {
  const isBp = (t) => t.path[0] === "breakpoint";
  const flat = tokens.filter((t) => !isBp(t) && typeof t.value === "string");
  const themed = tokens.filter((t) => !isBp(t) && typeof t.value === "object");
  const decl = (t, v) => `  ${cssName(t)}: ${v};`;
  const motion = tokens.filter((t) => t.path[0] === "motion");
  return [
    "/* GENERATED by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit. */",
    ":root {",
    ...flat.map((t) => decl(t, t.value)),
    "}",
    ':root, [data-iv-theme="light"], [data-iv-theme="system"] {',
    "  color-scheme: light;",
    ...themed.map((t) => decl(t, t.value.light)),
    "}",
    '[data-iv-theme="dark"] {',
    "  color-scheme: dark;",
    ...themed.map((t) => decl(t, t.value.dark)),
    "}",
    "@media (prefers-color-scheme: dark) {",
    '  [data-iv-theme="system"] {',
    "    color-scheme: dark;",
    ...themed.map((t) => "  " + decl(t, t.value.dark)),
    "  }",
    "}",
    "/* A theme scope re-applies text and background so nested scopes do not inherit the parent theme's computed colours. */",
    "[data-iv-theme] {",
    "  color: var(--iv-color-text);",
    "  background-color: var(--iv-color-bg);",
    "}",
    "@media (prefers-reduced-motion: reduce) {",
    "  :root {",
    ...motion.map((t) => "  " + decl(t, "0ms")),
    "  }",
    "}",
    "",
  ].join("\n");
}

export function emitCustomMedia(tokens) {
  const bps = tokens.filter((t) => t.path[0] === "breakpoint");
  return [
    "/* GENERATED by scripts/build-tokens.mjs. Breakpoints are resolved at build time by lightningcss. */",
    ...bps.map((t) => `@custom-media --iv-${t.path[1]} (min-width: ${t.value});`),
    "",
  ].join("\n");
}

export function emitBreakpointsJs(tokens) {
  const bps = tokens.filter((t) => t.path[0] === "breakpoint");
  return [
    "// GENERATED by scripts/build-tokens.mjs. Do not edit.",
    "/** Breakpoints as min-width media query strings, keyed by name. */",
    "export const breakpoints = Object.freeze({",
    ...bps.map((t) => `  ${JSON.stringify(t.path[1])}: ${JSON.stringify(`(min-width: ${t.value})`)},`),
    "});",
    "",
  ].join("\n");
}

export function emitJson(tokens) {
  const obj = {};
  for (const t of tokens) obj[cssName(t)] = { type: t.type, value: t.value };
  return JSON.stringify(obj, null, 2) + "\n";
}

const tokens = flatten(src);
mkdirSync(resolve(root, "dist/tokens"), { recursive: true });
writeFileSync(resolve(root, "src/css/tokens.css"), emitCss(tokens));
writeFileSync(resolve(root, "src/css/custom-media.css"), emitCustomMedia(tokens));
writeFileSync(resolve(root, "src/js/core/breakpoints.js"), emitBreakpointsJs(tokens));
writeFileSync(resolve(root, "dist/tokens/tokens.json"), emitJson(tokens));
console.log(`tokens: ${tokens.length} emitted`);
