// GENERATED by scripts/build-tokens.mjs. Do not edit.
/** Breakpoints as min-width media query strings, keyed by name. */
export const breakpoints = Object.freeze({
  "sm": "(min-width: 30em)",
  "md": "(min-width: 48em)",
  "lg": "(min-width: 64em)",
  "xl": "(min-width: 80em)",
  "2xl": "(min-width: 90em)",
});
